In [64]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


# Paqueterias

In [65]:
from pathlib import Path
import sys
import numpy as np

In [66]:
CURRENT_DIR = Path('.').resolve()
MODULES_DIR = CURRENT_DIR.parent.joinpath('src')
sys.path.append(str(MODULES_DIR))

In [67]:
import red_nueronal.red_neuronal as rn
import math_funciones.math_funciones as mf

-----
# Datos que usaremos para entrenar el modelo

Se tienen los siguintes datos con los cuales entrenaremos nuestra red neuronal

| A | B | C | Y |
|---|---|---|---|
| 0 | 0 | 1 | 0 |
| 0 | 1 | 1 | 1 |
| 1 | 0 | 1 | 1 |
| 1 | 1 | 1 | 0 |

In [68]:
a = np.array([[0, 0, 1],[0, 1, 1],[1,0,1],[1,1,1]])
y = np.array([[0],[1],[1],[0]])

-----
## Instaciamos nuestra red neuronal

In [69]:
red = rn.NeuralNetwork(a,y)

Podemos ver que de forma automatica, inicia con valores aleatorios para los pesos, los cuales son los siguentes:

In [70]:
print('weights1',red.weights1)
print('weights2',red.weights2)

weights1 [[0.5801586  0.38139754 0.16888782 0.02189162]
 [0.01085602 0.30110002 0.03577326 0.9703407 ]
 [0.90362595 0.49824703 0.24285637 0.70858382]]
weights2 [[0.49233401]
 [0.205994  ]
 [0.95766185]
 [0.62956663]]


Imprimos el primer y_output que genera:

In [71]:
red.feedforward()
red.backprop()
red.output

array([[0.8080028 ],
       [0.82767994],
       [0.82460281],
       [0.84241872]])

Ejecutamos pasos hacia adelante y hacia atras 3000 veces para entrenar a nuestra red neuronal, vemos que los resultados ahora se acercan mucho a los valores reales de **y**, lo que indica que ya esta entrenado de forma exitosa. 

In [72]:
for i in range(3000):
    red.feedforward()
    red.backprop()
    i+=1
print(red.output)

[[0.00896889]
 [0.98747349]
 [0.98742596]
 [0.0105536 ]]


Los pesos actuliazados son:

In [73]:
print('weights1',red.weights1)
print('weights2',red.weights2)

weights1 [[ 28.12190698   3.87278049  -0.06614089 -24.44303978]
 [-23.43387053   3.76560405  -0.13507324  29.08601132]
 [ -1.15469634  -2.31869853  -1.35372724  -1.1996668 ]]
weights2 [[-13.88462357]
 [ 22.38791352]
 [ -1.20696176]
 [-13.53577965]]


------
## Predicicon del modelo
Podemos aplicar el modelo para un nuevo valor y nos genera la siguente predicción

In [74]:
red.aplicar_modelo(np.array([[1,1,0]]))
print(red.prediction)

[[0.0048183]]
